// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyeS5p49eWYO_Qf194ZgIHr8vCfmy5c_I',
    appId: '1:46160699973:web:126f6e86c5114b3620b92c',
    messagingSenderId: '46160699973',
    projectId: 'doctracker-f3714',
    authDomain: 'doctracker-f3714.firebaseapp.com',
    storageBucket: 'doctracker-f3714.appspot.com',
    measurementId: 'G-10FWXVDKM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN6T2A3ZI-SjIK19R4n3LwYDejRQlrYtw',
    appId: '1:46160699973:android:df6be0c98a96849220b92c',
    messagingSenderId: '46160699973',
    projectId: 'doctracker-f3714',
    storageBucket: 'doctracker-f3714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF686OdBWuvqDnhJ7jF8PTP5DfXQA9xVk',
    appId: '1:46160699973:ios:c0a152ed88a449c620b92c',
    messagingSenderId: '46160699973',
    projectId: 'doctracker-f3714',
    storageBucket: 'doctracker-f3714.appspot.com',
    iosClientId: '46160699973-aj4bro49dlh87l08t1n4lhkhe1vi98bu.apps.googleusercontent.com',
    iosBundleId: 'com.example.docTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF686OdBWuvqDnhJ7jF8PTP5DfXQA9xVk',
    appId: '1:46160699973:ios:c0a152ed88a449c620b92c',
    messagingSenderId: '46160699973',
    projectId: 'doctracker-f3714',
    storageBucket: 'doctracker-f3714.appspot.com',
    iosClientId: '46160699973-aj4bro49dlh87l08t1n4lhkhe1vi98bu.apps.googleusercontent.com',
    iosBundleId: 'com.example.docTracker',
  );
}
